### ISSUE TITLE
[v1] No GIF support

### ISSUE THREAD

**Issue by bedeoverend** [SimplaElements/simpla-img#42]
In v1 we've moved to using native `img` elements, and then editing these images in `canvas`. This means that we support images that can be exported by canvas, which doesn't include GIFs. This issue is a discussion around this problem. 

There are [workarounds](http://stackoverflow.com/questions/3062229/animated-gif-in-html5-canvas), but they're incredibly heavy, and IMO not worth it for the small benefit of uploading GIFs. Perhaps a server side solution?

Another option would be to allow GIFs but without any editing functionality, so that it would just be a raw upload that never touches the canvas, but that could confuse things - the UX to explain this would need to be thought out. Perhaps this could be a property on `simpla-img` a là `plaintext` on `simpla-text`, just the img upload but with no editing capabilities?

**Comment by seaneking** [comment]
The only same way to support gifs is upload-only. Editing gifs (especially if we introduce more complex transforms in future) for this element is bonkers. It was a side perk of the v0 'fake editor' anyway, not a planed feature.

In terms of implementation and UX, I think it would be fine to just hide the cropper slider (and don't load file into canvas) when a gif is uploaded and re-enable it if an img is uploaded. That's better than just flat out not supporting gifs (think of blog posts, and demos eg: Simpla home page), and I think relatively easy to grok ("why can't I zoom in on this one? Because it's a gif I guess" vs. "I can't upload gifs? Argh!").

If we wanted to have some rudimentary gif editing support in future (playback control) we could chuck in `x-gif` - smells like bloat to me right now though.

**Comment by seaneking** [comment]
> small benefit of uploading gifs

I think you're underestimating just how much gifs are used on the web today. Simpla img must support them in some fashion IMO.

**Comment by bedeoverend** [comment]
Yeah I'm happy with all that. I'd say we do an implementation which is upload only, which hides the zoom bar. Can go from there, but I think that'll be good enough.

**Comment by bedeoverend** [comment]
Fixed in 9466da9c5f90d3b6f2984d2808cd991967300f1d
